### ISSUE TITLE
New FreeCAD UI tool for fetching online content (3D part geometry)

### ISSUE THREAD

**Issue by yorikvanhavre** [opencax/GSoC#39]
## Outline

Design a FreeCAD library tool that fetches the content online, without the need to download the whole library

## Details

FreeCAD possesses a vast library of parts submitted by users, hosted on https://github.com/FreeCAD/FreeCAD-library . This library is huge (> 1.5Gb) and currently the only way to use it is by installing (downloading) it entirely from the Addons Manager. We need a new tool that is able to access both an offline or online version of the library (downloaded on your computer or hosted on a git platform such as github or gitlab) and allow users to browse the contents and download and place objects in their current model. The tool shouldn't depend on a sole git platform as this library could be moved to some other platform in the future.

Optionally, it could also allow users to upload models.

## Expected Outcome

A new FreeCAD UI tool

### Skills

The student should have a good knowledge of Python or C++, and learn how to build interface tools with Qt/PySide/QtCreator

### Difficulty

Medium

### Additional Information

* Potential mentor(s): [Yorik](https://www.forum.freecadweb.org/memberlist.php?mode=viewprofile&u=68)
* Organization website: https://freecadweb.org
* Communication channels: https://https://forum.freecadweb.org

**Comment by yorikvanhavre** [comment]
Other FreeCAD ideas for 2021 at https://www.forum.freecadweb.org/viewtopic.php?f=8&t=54913

**Comment by yorikvanhavre** [comment]
@chennes has formulated some ideas on this question, be sure to check with him if interested in working on this

**Comment by yorikvanhavre** [comment]
This topic might become part of a bigger project sponsored by the FPA

**Comment by brlcad** [comment]
FreeCAD is now participating as their own GSoC org, congrats!

**Comment by senyasuper** [comment]
if it will be big enough to split, Im also ready to participate

**Comment by senyasuper** [comment]
Thanks for providing this information, some of these requirements sound a
bit complicated for me, but about a few of them I have some ideas of
implementation. So first question: is anyone already working on it or are
you waiting for official submission on GSoC? And the library that is
supposed to be implemented in FREECAD is this:
https://github.com/FreeCAD/FreeCAD-library? Also if I'm thinking of taking
175h hours of work, how many of those requirements are supposed to be done
by myself?

**Comment by yorikvanhavre** [comment]
@chennes is interested in working on this subject. I did the original setup of the library, and at the moment nobody is working on it. I also don't know of other GSoC proposals for it.

Indeed the whole "server" part is complex. But you could start working on the general design of a new library tool in FreeCAD, that would be able to take its sources from different platforms, and use our current GitHub library repository for now.

The actual migration of that content could be left out of your proposal, and be the matter for another later project.

It is not really a problem if you feel you don't have the knowledge to implement something. Many of us can help you with that. It's more important here to be ready and interested in exploring, communicating, and working with us to arrive to a good plan. If you are interested in working on this, I would basically concentrate on designing how such an application should work, deigning/mockuping UI components and behaviours, etc, and implementing up to where you will be able to go. In GSoC projects, delivering a finished result is not a mandatory point. The important is to dedicate work on the subject, and help the project to advance in that direction.

**Comment by senyasuper** [comment]
Yes, I'm interested in it, is FreeCAD forum an appropriate place to introduce myself and submit first version of proposal for feedback or there are other options to contact you?

**Comment by yorikvanhavre** [comment]
> (By "interested in working on this subject" @yorikvanhavre means that I am available to mentor you, not that I want to do it myself

Yes poor choice of words, sorry :sweat_smile:
