### ISSUE TITLE
Create a new KiCad importer

### ISSUE THREAD

**Issue by mikwielgus** [opencax/GSoC#46]
Outline
-------

Create a new importer for files from any EDA software for which there is no built-in importer yet.

Details
-------

A non-exhaustive list of possible EDA software:

- Easy (open source): Fritzing, gEDA, Horizon EDA, LibrePCB, JSchem, pcb-rnd
- Easy, but slightly harder (port existing importer): EasyEDA ([link](https://github.com/wokwi/easyeda2kicad), [link](https://github.com/RigoLigoRLC/LC2KiCad)), Zuken CR-5000 ([link](https://forum.kicad.info/t/zuken-cr-5000-to-kicad-converter/22923)), LTSpice ([link](https://github.com/laurentc2/LTspice2Kicad))
- Medium (text formats): Allegro ASCII, PADS ASCII, Mentor HyperLynx, SIMetrix, Micro-Cap, ...
- Hard (binary formats): Target 3001!, DipTrace, EAGLE < 5.91, Allegro, Mentor, ...

There are two FOSDEM talks around this topic to get a rough idea of the task:

- [Importing into KiCad from CADSTAR](https://archive.fosdem.org/2021/schedule/event/openhard_cadstar/)
- [Reverse-Engineering of (binary) File-Formats](https://archive.fosdem.org/2021/schedule/event/reverse_engineering/)

In case you want to write an importer for a proprietary EDA program, you need to have legal access to this software. You can use a demo or student version if it is available, or you may have some other means of access, like your university institute (please ask them beforehand). If you are unsure about this topic, choose one of the open-source tools instead.

Expected Outcome
----------------

An importer for files from EDA software for which there was no built-in importer. Depending on the complexity, this might include board, schematic and/or library import.

Project Properties
------------------

### Skills

- C++
- Basic knowledge of the EDA software the importer will be for

### Difficulty

Depends on the selected EDA package.

### Size

175 hours (schematic-only software like LTSpice, SIMetrix, Micro-Cap)
350 hours (software with both schematic and PCB layout)

### Additional Information

- Potential mentors:
    - [Roberto Fernandez Bautista](mailto:gsoc@kicad.org)
    - [Thomas Pointhuber](mailto:gsoc@kicad.org)
- Organization website: https://kicad.org
- Communication channels:
    - gsoc@kicad.org
    - [Discord channel](https://discord.gg/WhzyWZ5RaD)

**Comment by zingo** [comment]
For EasyEDA there is also https://github.com/RigoLigoRLC/LC2KiCad

**Comment by Trashman247** [comment]
Hello,

I have a strong interest in logic/circuit design and this project interests me for the GSoC. Just found out about GSoC and realized the deadline is coming soon, so I just wanted to get this comment in to notify as early as possible. I plan to comment soon with a more in depth proposal: I hope to get advice on crafting a project proposal for April 19th then! Please let me know if this works.

Thanks!

**Comment by mikwielgus** [comment]
Sure, go ahead. I recommend you to discuss your proposal with us on the Discord channel or via email before submitting.

**Comment by zingo** [comment]
Trashman247 If you (or anyone else) do this ping me (here or zingo@zingo.org) and I can package some current progress of my EasyEda json import try for you as as something to look at or get inspired of, or to use use base :).
I currently got to it to the point where the fun begins e.g. I can select import from the menu and select a file and it read in the json. Next step would be to dig out the needed stuff from the json struct and create KiCad stuff from it. My plan was to use the code from https://github.com/RigoLigoRLC/LC2KiCad to figure out the actual conversion (got ok from RigoLigoRLC about it) .

**Comment by Trashman247** [comment]
Thanks! I am just entering college and I don't think I have the skill set yet to take on open source. Don't know the future holds, but I'll come back for GSoC 2023! (or if your open to non-GSoC contributions, but it will still take some months for me to learn either way).
