### ISSUE TITLE
Create a KiCad to ODB++ exporter

### ISSUE THREAD

**Issue by mikwielgus** [opencax/GSoC#50]
Outline
-------

KiCad currently supports export to GenCAD, Gerber, Gerber X2 and IPC-D-356. These are commonly used, but many manufacturers would like the additional information contained in an ODB++ file.  This includes net information, board stackup, bill of materials, embedded stroke fonts as well as standard layer data.

Details
-------

The ODB++ Design website provides a reference viewer to verify data output. There are many examples in the existing Gerber and GenCAD exporters to use for implementation frameworks.

Relevant Links:

- https://odbplusplus.com/design
- https://gitlab.com/kicad/code/kicad/-/issues/2019

Expected Outcome
----------------

An ODB++ exporter that can generate standard ODB++ files using existing v7 KiCad features.

Project Properties
------------------

### Skills

- C++
- Basic knowledge of EDA software concepts

### Difficulty

Medium

### Size

350 hours

### Additional Information

- Potential mentors:
    - [Seth Hillbrand](mailto:gsoc@kicad.org)
- Organization website: https://kicad.org
- Communication channels:
    - gsoc@kicad.org
    - [Discord channel](https://discord.gg/WhzyWZ5RaD)

**Comment by hrithik254** [comment]
where can i access the plugin?
