### ISSUE TITLE
Improve FreeCAD's OpenSCAD importer handling of Hull Requests

### ISSUE THREAD

**Issue by KeithSloan** [opencax/GSoC#61]
## Outline
At present the importer calls openscad to perform the hull operation and creates a FreeCAD mesh type object from the returned result. For certain subsets of hull requests a hull of Brep Shape objects can be performed which is not only faster but has a better outcome. The importer in the workbench [OpenSCAD Alternate Importer](https://github.com/KeithSloan/OpenSCAD_Alt_Import) has made a start in this direction.
## Details
Improve and add to the number of hull requests that can be handled without resorting to Meshing and calling the openscad executable

- Study how the importer parses OpenSCAD csg files with lex
- Study what a hull request does
- Research and study special case hull requests being handled by Alternate importer
- Research and document additional special cases
- Code handling of new case
- Create test cases
- Add test cases to existing OpenSCAD workbench test cases

## Expected Outcome

- Add special case Hull requests to main OpenSCAD importer

### Skills

- Python coding
- Solid Graphics Geometry

### Difficulty 
medium

### Additional Information

* Potential mentor(s): [Keith Sloan]
* Organization website: https://freecadweb.org/
* Communication channels: [https://forum.freecadweb.org](https://https//forum.freecadweb.org) slack

**Comment by brlcad** [comment]
FreeCAD is now participating as their own GSoC org
