### ISSUE TITLE
Improve FreeCAD - OpenSCAD interaction

### ISSUE THREAD

**Issue by KeithSloan** [opencax/GSoC#62]
## Outline
FreeCAD 0.20 improved the addElement facility of the OpenSCAD workbench however this could still be improved further

## Details
The addElement is basically an editor for OpenSCAD script with the option to have output to FreeCAD document and
and report any errors in a window.

Research ideas on improving direct interaction with OpenSCAD from FreeCAD

With
- @chennes
- @KeithSloan52

Own ideas

- Decide on plan
- Implement new facility for FreeCAD / OpenSCAD interaction.

## Expected Outcome
New facility in FreeCAD to edit OpenSCAD scripts and have their output create FreeCAD objects in the current document

### Skills
- Qt
- Python
- OpenSCAD scripting

### Difficulty 
Medium

### Additional Information

* Potential mentor(s): [Keith Sloan]
* Organization website: https://freecadweb.org/
* Communication channels: https://forum.freecadweb.org) slack

**Comment by brlcad** [comment]
FreeCAD is now participating as their own GSoC org
