### ISSUE TITLE
GSoC 2023: On-Machine Inspection project has a broken link

### ISSUE THREAD

**Issue by airvzxf** [opencax/GSoC#74]
Regarding the official [Wiki for GSoC 2023](https://wiki.freecad.org/Google_Summer_of_Code_2023), the project [On-Machine Inspection](https://github.com/opencax/GSoC/issues/8588) has a broken link.

![List of the projects](https://user-images.githubusercontent.com/831380/222030282-aa9be755-fcbe-4756-b114-6ce789515bdc.png)

**Comment by brlcad** [comment]
It doesn't appear to just be a broken link -- there is no issue with that name.  I believe I found that on FreeCAD's issue list, however, so that seems to be the error.  It should link to https://github.com/FreeCAD/FreeCAD/issues/8588
