### ISSUE TITLE
Update Appleseed to Python3

### ISSUE THREAD

**Issue by brlcad** [opencax/GSoC#75]
## Outline
This project entails fully updating Appleseed to Python3.

## Details

Appleseed is mostly written in C/C++ but uses Python for scripting and GUI purposes.  Appleseed is also integrated into various modeling environments (e.g., Blenderseed) via Python.  They were developed against Python2 and haven't yet been updated.

## Expected Outcome

Expected are updates to Appleseed's Python build logic, Python code, and integrations so that they work with a Python3 that adheres to a specified vfx platform: https://vfxplatform.com 

You'll be expected to make the necessary changes, produce and test working builds for multiple platforms, and get 3rd party integrations (e.g., Blenderseed) working with the latest too.

You are welcome to make this a Medium or Long project, with deliverables specified accordingly.  Feel free to expand the scope if there are related tasks you want to accomplish.

### Difficulty 
easy

### Size 
medium

### Additional Information

* Potential mentor(s): [Sean Morrison](mailto:devs@brlcad.org)
* Organization website: https://appleseedhq.net
* Communication channels: https://brlcad.zulipchat.com

**Comment by brlcad** [comment]
Hello @AtrikeshM -- I suggest you join our Zulip chat for ongoing discussion, but you can get started by downloading and getting familiarized with Appleseed and/or Blenderseed.  Compiling Appleseed from source is another good way to get familiarized.  Research the current state of the code and then ask questions so you can frame a detailed project proposal.

**Comment by geckguy** [comment]
Hi! i'd like to work on this issue, anyway I can have a talk with mentors and get detailed info on the project

**Comment by brlcad** [comment]
Hello @geckguy and thanks for your interest.  Feel free to join on Appleseed's Discord to talk more interactively, or join BRL-CAD's Zulip.  Ask lots of good questions!

**Comment by geckguy** [comment]
Okay, I will do that! thank you

**Comment by LukasMoll** [comment]
Hello, my name is Lukas Molleman, and I am interested in this project. I have experience working as a developer with Python in both startup and big tech environments. I am currently pursuing a degree in computer science engineering.

I am confident that my skills and experience make me an excellent fit for this project. How can I demonstrate my abilities and start contributing?

**Comment by drossberg** [comment]
Hi @LukasMoll, please join our Zulip channel (the address is in the description above). That's the best place for discussions with the mentors.

**Comment by brlcad** [comment]
This task was worked and completed in GSoC 2023.
