### ISSUE TITLE
Adding CAD Customization to OpenCAx

### ISSUE THREAD

**Issue by purushottamnawale** [opencax/GSoC#79]
## Outline
CAD customization is essential in today's world as it improves workflow efficiency, accuracy, and facilitates better collaboration among team members. The project aims to add support for CAD customization to the OpenCAx software, which will allow users to create custom 3D models using Python and C++ programming.

## Technical Details
The project will require the team to have a strong understanding of both Python and C++ programming languages. The student will need to explore the OpenCAx codebase, understand its architecture, and identify the areas that require modification to enable CAD customization.

The project will involve adding a new module to OpenCAx that provides an API for creating custom 3D models using Python and C++. The API will be designed to support commonly used CAD functions, such as creating geometries, applying materials, and manipulating objects. The student will need to ensure that the new module integrates well with the existing OpenCAx codebase and does not cause any regressions or bugs.

## Deliverables
- A working module that enables CAD customization in OpenCAx software
- The ability to create custom 3D models using Python and C++ programming
- Documentation of the new module and its APIs
- A set of test cases that ensure the module's functionality and quality
- Code contributions to the OpenCAx community that adhere to their coding standards and guidelines.

## Expected Outcome
The expected outcome of the project is to provide support for basic 3D modeling using Python and C++ programming within the OpenCAx software. This feature will enable users to create custom models, streamline their workflow, and improve collaboration among team members.

## Future Possibilities 
The project's future possibilities include the potential to expand the software's capabilities further, adding more advanced customization features and enabling integration with other software applications.

### Additional Information

* Potential mentor(s): [NAME](https://)
* Organization website: https://
* Communication channels: https://******.zulipchat.com

**Comment by t-paul** [comment]
Please explain what that is supposed to be. Are you affiliated with any of the projects collecting topics for GSoC here.
