### ISSUE TITLE
Electronic Simulation Application

### ISSUE THREAD

**Issue by slack-uj** [opencax/GSoC#80]
## Outline
I want to create a **simple electronic simulation software** that can solve the problems arising in undegraduate-college level courses for computer engineering,electronic engineering,etc.

## Details
Electronic problems related with particular course (say BE COMPUTER,POKHARA UNIVERSITY) will be focused.
## Expected Outcome
A fully functional simulation software that can solve all the electronic circuit problems for undergraduate levels.
## Future Possibilities 
This project can be accomplished and extended to widespread horizon.....But this is only focusing upon college problems
to help students solve and understand the electronic problems clearly.
## Project Properties
It is intended to obtain:
                                          1)a fully packaged application software
                                           2)a web-page for online interaction
### Skills
C....(for coding)
C++....(for coding)
Qt.....or any other equivalent.....(for gui application )
web-development

### Difficulty 
medium----**any newbie can accomplish if interested**
### Additional Information
Hello World!
I am a newbie,a undergraduate student.I want to participate in GSoC.If you are interested please reply or contact me.
We have only 48 hours left to submit the proposal!
* Potential mentor(s): [NAME](https://)
* Organization website: https://
* Communication channels: https://******.zulipchat.com
*  my email: slackuj@gmail.com------what'sapp : +9779840859551

**Comment by t-paul** [comment]
Sorry, but this does not relate to any of the projects (which are existing CAD related application, which you should have found on the website).

Proposing ideas other than the ones provided, is generally ok, but it would need to fit with one of the applications collaborating here in scope of GSoC. Proposing a totally different application with a wildly unrealistic timeline is not helping anyone. 

Please go through the documentation posted at https://developers.google.com/open-source/gsoc/help/student-advice - It's indeed not much time till the application period closes, so use that time wisely.
